# -*- coding: utf-8 -*-
# trend/__init__.py

from .alligator_bands import alligator_bands
from .archer_moving_averages_trends import archer_moving_averages_trends
from .arnaud_legoux_moving_average import arnaud_legoux_moving_average
from .aroon import aroon
from .average_directional_index import average_directional_index
from .bollinger_trend import bollinger_trend
from .bollinger_trend_fast_with_ma import bollinger_trend_fast_with_ma
from .breakouts import breakouts
from .chande_kroll_stop import chande_kroll_stop
from .choppiness_index import choppiness_index
from .cross_signals import cross_signals
from .decay import decay
from .decreasing import decreasing
from .detrended_price_oscillator import detrended_price_oscillator
from .double_exponential_moving_average import double_exponential_moving_average
from .exponential_moving_average import exponential_moving_average
from .fractal_weighted_moving_average import fractal_weighted_moving_average
from .holt_winters_moving_average import holt_winters_moving_average
from .hull_moving_average import hull_moving_average
from .increasing import increasing
from .jurik_moving_average import jurik_moving_average
from .least_squares_moving_average import least_squares_moving_average
from .long_run import long_run
from .mcginley_dynamic import mcginley_dynamic
from .parabolic_sar import parabolic_sar
from .pascals_weighted_moving_average import pascals_weighted_moving_average
from .percent_price_channel import percent_price_channel
from .pmax import pmax
from .price_channel import price_channel
from .q_stick import q_stick
from .range_filter import range_filter
from .rolling_moving_average import rolling_moving_average
from .sequential_weighted_moving_average import sequential_weighted_moving_average
from .short_run import short_run
from .simple_moving_average import simple_moving_average
from .sine_weighted_moving_average import sine_weighted_moving_average
from .ssl_channels import ssl_channels
from .ssl_channels_atr import ssl_channels_atr
from .t3_average import t3_average
from .trend_signals import trend_signals
from .triangular_moving_average import triangular_moving_average
from .triple_exponential_moving_average import triple_exponential_moving_average
from .ttm_trend import ttm_trend
from .ut_bot import ut_bot
from .variable_index_dynamic_average import variable_index_dynamic_average
from .vertical_horizontal_filter import vertical_horizontal_filter
from .vortex_indicator import vortex_indicator
from .volume_weighted_moving_average import volume_weighted_moving_average
from .volumatic_variable_index_dynamic_average import volumatic_variable_index_dynamic_average
from .weighted_moving_average import weighted_moving_average
from .zero_exponential_moving_average import zero_exponential_moving_average
from .zero_lag_exponential_moving_average import zero_lag_exponential_moving_average
from .supertrend import supertrend
from .gaussian_channel import gaussian_channel